default_order_by: "{created}"

fields:
  id:
    name: "event id"
    use_as_id: true

  day:
    name: "event day"
    query:
      type: Range
      min: day_min
      max: day_max

  type:
    name: "event type"
    query:
      type: NumericTag

  category:
    name: "event category"
    query:
      type: NumericTag
      aliases:
        PLAYS: 0
        GAME: 0
        CHANGES: 1
        SPECIAL: 2
        ABILITIES: 2
        OUTCOMES: 3
        NARRATIVE: 4

  phase:
    name: "event phase"
    query:
      type: Range
      min: phase_min
      max: phase_max
      aliases:
        GODS_DAY: 0
        PRESEASON: 1
        EARLSEASON: 2
        EARLSIESTA: 3
        MIDSEASON: 4
        LATESIESTA: 5
        LATESEASON: 6
        ENDSEASON: 7
        PREPOSTSEASON: 8
        EARLPOSTSEASON: 9
        EARLPOSTSEASONEND: 10
        WILDCARDEVENING: 10
        LATEPOSTSEASON: 11
        POSTSEASONEND: 12
        ELECTION: 13
        SPECIAL: 14
        SPECIALEVENT: 14

  season:
    name: "event season"
    query:
      type: Range
      min: season_min
      max: season_max

  created:
    name: "event timestamp"
    converter:
      from: DateTimeString
      to: Timestamp
    query:
      type: Range
      min: after
      max: before

  gameTags:
    name: "event game tags"

  playerTags:
    name: "event player tags"

  teamTags:
    name: "event team tags"

  tournament:
    name: "event tournament"
    query:
      type: Range
      min: tournament_min
      max: tournament_max

  description:
    name: "event description"
    query:
      type: Fulltext
      lang: english

  metadata:
    name: "event metadata"
    query:
      type: Nested

  metadata._eventually_ingest_time:
    name: "ingest time filter"
    query:
      type: Range
      min: ingest_min
      max: ingest_max

  metadata.redacted:
    name: "is this redacted?"
    query:
      type: Bool

  metadata.scales:
    name: "amount of upscales"
    query:
      type: Range
      min: scales_min
      max: scales_max

  metadata.being:
    name: "divinity"
    query:
      type: NumericTag
      aliases:
        EMERGENCY: -1
        EMERGENCY_ALERT: -1
        SHELLED_ONE: 0
        PEANUT: 0
        MONITOR: 1
        BINKY: 1
        COIN: 2
        GIRLBOSS: 2
        READER: 3
        MICROPHONE: 4
        LOOTCRATES: 5
        NAMERIFEHT: 6
