services:
  monitor:
    image: allieee/rustventually:server
    environment:
      - "DB_URL=postgres://eventuallie:a@eventually_db/eventually"
      - "POLL_DELAY=1000"
      - "RUST_LOG=debug"
    command: ["./monitor"]

  rustventually:
    image: allieee/rustventually:server
    ports:
      - "4445:4445"
    build: ./eventually
    environment:
      - ROCKET_DATABASES={eventually={url=postgres://eventuallie:a@eventually_db/eventually}}
      - RUST_LOG=debug
      - ROCKET_LOG_LEVEL=debug
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=4445

  eventually_db:
    image: eventually_postgres
    build: ./db
    environment:
      - POSTGRES_USER=eventuallie
      - POSTGRES_PASSWORD=a
      - POSTGRES_DB=eventually
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
