version: '3'
services:
  redis:
    image: redislabs/redisearch:latest
    restart: always
    command: redis-server /redis.conf
    volumes:
      - redis_storage:/data
      - ./redis.conf:/redis.conf
  consumer:
    image: allieee/eventually:consumer
    command: python3 monitor.py --url redis://redis
  api:
    image: allieee/eventually:api
    ports:
      - "8080:80"

volumes:
  redis_storage:
