name: docker_push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push search backend
        uses: docker/build-push-action@v2
        with:
          context: ./eventually
          push: true
          tags: allieee/rustventually:server
      -
        name: Build and push search db
        uses: docker/build-push-action@v2
        with:
          context: ./db
          push: true
          tags: allieee/rustventually:db
