name: docker_push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push search backend
        uses: docker/build-push-action@v2
        with:
          context: ./eventually
          push: true
          tags: |
            ghcr.io/alisww/eventually:server
            ghcr.io/alisww/eventually:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/alisww/eventually:server
          cache-to: type=inline
      -
        name: Build and push search db
        uses: docker/build-push-action@v2
        with:
          context: ./db
          push: true
          tags: |
            ghcr.io/alisww/eventually:${{ github.sha }}s
            ghcr.io/alisww/eventually:db
          cache-from: type=registry,ref=ghcr.io/alisww/eventually:db
          cache-to: type=inline
